apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcphub-data-pvc
  labels:
    app: mcphub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default  # AKS 기본 스토리지 클래스 (default 또는 managed-csi 사용 가능)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default  # AKS 기본 스토리지 클래스 (default 또는 managed-csi 사용 가능) 