apiVersion: v1
kind: Service
metadata:
  name: mcphub-service
  namespace: mcphub
  labels:
    app: mcphub
spec:
  selector:
    app: mcphub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
  type: ClusterIP 